apiVersion: apps/v1
kind: Deployment
metadata:
  name: german
  namespace: translator-app
  labels:
    app: translator-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: german
  template:
    metadata:
      labels:
        app: german
    spec:
      containers:
        - name: german
          image: dts/german
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: SERVER_PORT
              value: "8084"

            - name: kafka.client.id
              value: german

            - name: zipkin.service.name
              value: GermanProcessor

            - name: kafka.consumer.group.id
              value: german

            - name: translator.target
              value: DE
---
apiVersion: v1
kind: Service
metadata:
  name: german
  namespace: translator-app
  labels:
    app: translator-app
spec:
  type: ClusterIP
  selector:
    app: german
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084